[32mINFO    [0m mobile_framework_logger:conftest.py:30 🚀 Starting local Appium server for this session...
[32mINFO    [0m root:appium_server.py:33 🚀 Starting Appium server...
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e029be0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e029d60>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e029ee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04e1f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04e310>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04e4c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04e7f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04e970>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e017eb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e017e80>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e029100>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e029040>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04e640>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04e100>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04ebb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04eee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e0730a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e073220>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e073550>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e0736d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e04edf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e073430>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e073940>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e073ac0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e073df0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e073f70>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e089130>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e089460>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e0895e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e089760>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e089a90>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e089c10>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e017ca0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e089d00>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e089e80>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e0a8070>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e0a8370>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e0a84f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f827e0a8670>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/status
[32mINFO    [0m root:appium_server.py:21 ✅ Appium is running at http://127.0.0.1:4723/wd/hub/status
[32mINFO    [0m root:appium_server.py:40 ✅ Appium server started successfully after 1 seconds.
[32mINFO    [0m mobile_framework_logger:conftest.py:23 🔍 Selected platform: ios
[32mINFO    [0m mobile_framework_logger:conftest.py:41 🚗 Initializing driver for platform: ios
[32mINFO    [0m root:driver_manager.py:17 🔍 Checking CONFIG for platform: ios
[32mINFO    [0m root:driver_manager.py:34 🚀 Starting Appium driver for ios (None) with capabilities: {'platformName': 'iOS', 'appium:app': '/Users/susannakarapetyan/gap_mobile/mobile_automation_framework/apps/Genius-QA.app', 'appium:deviceName': 'iPhone 14 Pro', 'appium:platformVersion': '16.4', 'appium:automationName': 'XCUITest', 'appium:useNewWDA': True, 'appium:autoAcceptAlerts': True, 'appium:autoDismissAlerts': True, 'appium:wdaLocalPort': 8100, 'appium:wdaStartupRetries': 2, 'appium:wdaLaunchTimeout': 60000, 'server_url': 'http://127.0.0.1:4723/wd/hub'}
[32mINFO    [0m root:driver_manager.py:47 ✅ IOS driver for None started.
[32mINFO    [0m mobile_framework_logger:create_genius_team_successfully_tests.py:22 🔹 Setting up Login Test
[32mINFO    [0m mobile_framework_logger:create_genius_team_successfully_tests.py:33 🔍 Running on platform: iOS
[32mINFO    [0m mobile_framework_logger:login_page.py:12 🔍 Initializing LoginPage with platform: iOS
[32mINFO    [0m mobile_framework_logger:login_page.py:23 🔄 Verifying that the login screen is displayed on iOS...
[32mINFO    [0m mobile_framework_logger:login_page.py:31 ✅ Login screen is displayed on iOS.
[32mINFO    [0m mobile_framework_logger:create_genius_team_successfully_tests.py:48 🔹 Running valid login test on: iOS
[32mINFO    [0m mobile_framework_logger:create_genius_team_successfully_tests.py:52 🔐 Logging in with: NewLGOBCO1@mailinator.com / qwe123QWE!@#
[32mINFO    [0m mobile_framework_logger:login_page.py:39 🔹 Performing valid login on iOS with email: NewLGOBCO1@mailinator.com
[32mINFO    [0m mobile_framework_logger:base_page.py:93 ✅ Sent keys to ('-ios predicate string', 'value == "Email"'): NewLGOBCO1@mailinator.com
[32mINFO    [0m mobile_framework_logger:base_page.py:93 ✅ Sent keys to ('-ios predicate string', 'value == "Password"'): qwe123QWE!@#
[32mINFO    [0m mobile_framework_logger:base_page.py:37 ⏳ Waiting for element to be visible: ('-ios predicate string', 'value == "Sign In"')
[32mINFO    [0m mobile_framework_logger:base_page.py:40 ✅ Clicked on ('-ios predicate string', 'value == "Sign In"')
[32mINFO    [0m mobile_framework_logger:login_page.py:54 ✅ Login button clicked successfully.
[32mINFO    [0m mobile_framework_logger:dashboard_page.py:34 ✅ Dashboard tab is visible on the Dashboard.
[32mINFO    [0m mobile_framework_logger:create_genius_team_successfully_tests.py:55 ✅ Login test completed successfully!
[32mINFO    [0m mobile_framework_logger:dashboard_page.py:54 🔹 Clicking GM tab...
[32mINFO    [0m mobile_framework_logger:base_page.py:37 ⏳ Waiting for element to be visible: ('-ios predicate string', 'label == "icon genius meter"')
[32mINFO    [0m mobile_framework_logger:base_page.py:40 ✅ Clicked on ('-ios predicate string', 'label == "icon genius meter"')
[32mINFO    [0m mobile_framework_logger:dashboard_page.py:56 ✅ GM tab clicked successfully!
[32mINFO    [0m mobile_framework_logger:GM_page.py:24 🔹 Scrolling to the bottom of the GM page...
[32mINFO    [0m mobile_framework_logger:base_page.py:239 🔍 Element 'create_team_btn' not initially visible. Starting scroll...
[32mINFO    [0m mobile_framework_logger:base_page.py:246 📱 iOS: Scrolling up
[32mINFO    [0m mobile_framework_logger:base_page.py:278 🔄 Still not visible after 1 scroll(s)...
[32mINFO    [0m mobile_framework_logger:base_page.py:246 📱 iOS: Scrolling up
[32mINFO    [0m mobile_framework_logger:base_page.py:278 🔄 Still not visible after 2 scroll(s)...
[32mINFO    [0m mobile_framework_logger:base_page.py:246 📱 iOS: Scrolling up
[32mINFO    [0m mobile_framework_logger:base_page.py:278 🔄 Still not visible after 3 scroll(s)...
[32mINFO    [0m mobile_framework_logger:base_page.py:246 📱 iOS: Scrolling up
[32mINFO    [0m mobile_framework_logger:base_page.py:278 🔄 Still not visible after 4 scroll(s)...
[32mINFO    [0m mobile_framework_logger:base_page.py:246 📱 iOS: Scrolling up
[32mINFO    [0m mobile_framework_logger:base_page.py:278 🔄 Still not visible after 5 scroll(s)...
[33mWARNING [0m mobile_framework_logger:base_page.py:280 ⚠️ Max scrolls reached. Element 'create_team_btn' not found.
[32mINFO    [0m mobile_framework_logger:GM_page.py:29 ✅ Reached the bottom of the GM page.
[32mINFO    [0m mobile_framework_logger:GM_page.py:63 🔹 Clicking Create a team...
[32mINFO    [0m mobile_framework_logger:base_page.py:37 ⏳ Waiting for element to be visible: ('-ios predicate string', 'label == "Create a Team" AND name == "Create a Team" AND type == "XCUIElementTypeButton"')
[32mINFO    [0m mobile_framework_logger:base_page.py:40 ✅ Clicked on ('-ios predicate string', 'label == "Create a Team" AND name == "Create a Team" AND type == "XCUIElementTypeButton"')
[32mINFO    [0m mobile_framework_logger:GM_page.py:65 ✅ Create a team is clicked successfully!
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:39 ✅ create_team_title is visible on the Create a team screen.
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:103 📝 Filling out GM team creation fields with:
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:104    • Team Name: $*uLS4sK%cH0
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:105    • Project Name: JZ}_-nc2H5uW
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:106    • Outcome: @s{b9N{^2+W5
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:117 🔹 Focusing and typing into Team Name field...
[32mINFO    [0m mobile_framework_logger:base_page.py:37 ⏳ Waiting for element to be visible: ('accessibility id', 'Enter team name…')
[32mINFO    [0m mobile_framework_logger:base_page.py:40 ✅ Clicked on ('accessibility id', 'Enter team name…')
[32mINFO    [0m mobile_framework_logger:base_page.py:93 ✅ Sent keys to ('accessibility id', 'Team Name'): $*uLS4sK%cH0
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:122 🔹 Focusing and typing into Project Name field...
[32mINFO    [0m mobile_framework_logger:base_page.py:37 ⏳ Waiting for element to be visible: ('accessibility id', 'Enter project name…')
[32mINFO    [0m mobile_framework_logger:base_page.py:40 ✅ Clicked on ('accessibility id', 'Enter project name…')
[32mINFO    [0m mobile_framework_logger:base_page.py:93 ✅ Sent keys to ('accessibility id', 'Project Name'): JZ}_-nc2H5uW
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:127 🔹 Focusing and typing into Outcome field...
[32mINFO    [0m mobile_framework_logger:base_page.py:37 ⏳ Waiting for element to be visible: ('accessibility id', 'Enter outcome…')
[32mINFO    [0m mobile_framework_logger:base_page.py:40 ✅ Clicked on ('accessibility id', 'Enter outcome…')
[32mINFO    [0m mobile_framework_logger:base_page.py:93 ✅ Sent keys to ('accessibility id', 'Outcome'): @s{b9N{^2+W5
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:130 ✅ GM team form filled successfully.
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:168 ⏳ Waiting for 'Submit' button to be visible...
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:170 ✅ 'Submit' button is visible. Clicking now...
[32mINFO    [0m mobile_framework_logger:GM_create_team.py:172 ✅ 'Submit' button clicked successfully.
[32mINFO    [0m mobile_framework_logger:GM_invite_to_team_page.py:52 🔹 Clicking Create add_members_btn...
[32mINFO    [0m mobile_framework_logger:base_page.py:37 ⏳ Waiting for element to be visible: ('-ios predicate string', 'label == "Add Members" AND name == "Add Members" AND type == "XCUIElementTypeButton"')
[32mINFO    [0m mobile_framework_logger:base_page.py:40 ✅ Clicked on ('-ios predicate string', 'label == "Add Members" AND name == "Add Members" AND type == "XCUIElementTypeButton"')
[32mINFO    [0m mobile_framework_logger:GM_invite_to_team_page.py:54 ✅ Add Members button is clicked successfully!
[32mINFO    [0m mobile_framework_logger:GM_invite_find_people_list.py:67 🔍 Searching for user: 'susanna'
[32mINFO    [0m mobile_framework_logger:base_page.py:93 ✅ Sent keys to ('-ios class chain', '**/XCUIElementTypeSearchField[`label == "Search"`][2]'): susanna
[33mWARNING [0m mobile_framework_logger:base_page.py:85 ⚠️ Could not hide keyboard: Message: Error Domain=com.facebook.WebDriverAgent Code=1 "Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test." UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}
Stacktrace:
InvalidElementStateError: Error Domain=com.facebook.WebDriverAgent Code=1 "Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test." UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}
    at errorFromW3CJsonCode (/Users/susannakarapetyan/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1110:25)
    at ProxyRequestError.getActualError (/Users/susannakarapetyan/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:979:14)
    at JWProxy.command (/Users/susannakarapetyan/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:351:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at XCUITestDriver.proxyCommand (/Users/susannakarapetyan/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
    at XCUITestDriver.mobileHideKeyboard (/Users/susannakarapetyan/.appium/node_modules/appium-xcuitest-driver/lib/commands/keyboard.js:23:5)
    at XCUITestDriver.executeMethod (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:61:12)
    at XCUITestDriver.execute (/Users/susannakarapetyan/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:117:14)
[32mINFO    [0m mobile_framework_logger:GM_invite_find_people_list.py:81 ⏳ Waiting for user to appear in search results...
[31m[1mERROR   [0m mobile_framework_logger:GM_invite_find_people_list.py:100 ❌ User 'susanna' not found within 5 seconds.
[32mINFO    [0m mobile_framework_logger:conftest.py:53 🛑 Quitting driver after test...
[32mINFO    [0m mobile_framework_logger:conftest.py:33 🛑 Stopping Appium server...
[32mINFO    [0m root:appium_server.py:50 🛑 Stopping Appium server...
[32mINFO    [0m root:appium_server.py:52 ✅ Appium server stopped.